name: Tests

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]

        steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Set up Python
          uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .[dev]

        - name: Run tests with pytest
          run: pytest tests/ --cov=qickit --cov-report=xml

        - name: Run mypy
          run: mypy qickit

        - name: Run ruff
          run: ruff check qickit

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@1e68e06f1dbfde0e4cefc87efeba9e4643565303 # v5.1.2
          with:
            files: ./coverage.xml
