name: Tests

on:
    workflow_dispatch:
    push:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pydantic==2.6.4

        - name: Run tests with pytest
          run: |
            pip install pytest
            pytest tests

        - name: Run mypy
          run: |
            pip install mypy
            mypy qickit

        - name: Run ruff
          run: |
            pip install ruff
            ruff check qickit

        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v4.0.1
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: Qualition/QICKIT